In [1]:
# import dependencies
import pandas as pd

In [2]:
# read csv

eighteen_data = pd.read_csv("data/2018.csv")
twentyone_data = pd.read_csv("data/world-happiness-report-2021.csv")

og_eighteen_df = eighteen_data
og_twentyone_df = twentyone_data

In [3]:
# Make copy 'eighteen_df' to rename columns
eighteen_df = og_eighteen_df.copy()

# Make copy 'twentyone_df' to rename columns
twentyone_df = og_twentyone_df.copy()

In [4]:
#ADD YEAR COLUMNS TO 2018 AND 2021 DATAFRAMES

# Find length of 2018 data frame
eighteen_df_len = og_eighteen_df['Overall rank'].unique()

# Find length of 2021 data frame
twentyone_df_len = og_twentyone_df['Country name'].unique()
 

#Create an empty list 'eighteen_df_year_values' to hold
eighteen_df_year_values = []

#Create an empty list 'twentyone_df_year_values' to hold
twentyone_df_year_values = []

# Add '2018' Values to eighteen_df_year_values
for i in range(len(eighteen_df_len)):
    eighteen_df_year_values.append('2018')
    

# Add '2021' Values to twentyone_df_year_values
for i in range(len(twentyone_df_len)):
    twentyone_df_year_values.append('2021')

# Add Year Column to 'eighteen_df' data frame and name column 'Year'
eighteen_df.insert(0, "Year", eighteen_df_year_values)

# Add Year Column to 'twentyone_df' data frame and name column 'Year'
twentyone_df.insert(0, "Year", twentyone_df_year_values)

In [5]:
# Rename 2018 dataframe Columns

# 'Overall rank' -> 'Happiness_Rank'
eighteen_df.rename(columns = {'Overall rank':'Happiness_Rank'}, inplace = True)

# 'Country or region' -> 'Country'
eighteen_df.rename(columns = {'Country or region':'Country'}, inplace = True)

# Copy 'Country or region' column to create a region column with the same values
# 'Country or region' -> 'Region'
eighteen_df['Region'] = eighteen_df['Country']

# 'Score' -> 'Happiness_Score'
eighteen_df.rename(columns = {'Score':'Happiness_Score'}, inplace = True)

# 'GDP per capita' -> 'Economy_GDP'
eighteen_df.rename(columns = {'GDP per capita':'Economy_GDP'}, inplace = True)

# 'Social support' -> 'Family' #UNSURE
eighteen_df.rename(columns = {'Social support':'Family'}, inplace = True)

# 'Healthy life expectancy' -> 'Life_Expectancy'
eighteen_df.rename(columns = {'Healthy life expectancy':'Life_Expectancy'}, inplace = True)

# 'Freedom to make life choices' -> 'Freedom'
eighteen_df.rename(columns = {'Freedom to make life choices':'Freedom'}, inplace = True)


# 'Perceptions of corruption' -> 'Trust_in_Gov'
eighteen_df.rename(columns = {'Perceptions of corruption':'Trust_in_Gov'}, inplace = True)
eighteen_df

# add dystopia column
eighteen_df['Dystopia_Residual']=""

# Reorder columns

,Year,Happiness_Rank,Country,Happiness_Score,Economy_GDP,Family,Life_Expectancy,Freedom,Generosity,Trust_in_Gov,Region,Dystopia_Residual
0,2018,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393,Finland,
1,2018,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340,Norway,
2,2018,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408,Denmark,
3,2018,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138,Iceland,
4,2018,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357,Switzerland,
...,...,...,...,...,...,...,...,...,...,...,...,...
151,2018,152,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064,Yemen,
152,2018,153,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097,Tanzania,
153,2018,154,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106,South Sudan,
154,2018,155,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038,Central African Republic,
155,2018,156,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076,Burundi,

In [6]:
# Set 'twentyone_df' index column values as new 'Happiness_Rank' column
twentyone_df.reset_index(inplace=True)

In [7]:
# # Rename 2021 dataframe Columns

# 'index' -> 'Happiness_Rank'
twentyone_df.rename(columns = {'index':'Happiness_Rank'}, inplace = True)

# 'Country name' -> 'Country'
twentyone_df.rename(columns = {'Country name':'Country'}, inplace = True)

# 'Regional indicator' -> 'Region'
twentyone_df.rename(columns = {'Regional indicator':'Region'}, inplace = True)

# 'Ladder score' -> 'Happiness_Score'
twentyone_df.rename(columns = {'Ladder score':'Happiness_Score'}, inplace = True)

# 'Logged GDP per capita' -> 'Economy_GDP'
twentyone_df.rename(columns = {'Logged GDP per capita':'Economy_GDP'}, inplace = True)

# 'Social support' -> 'Family' #UNSURE
twentyone_df.rename(columns = {'Social support':'Family'}, inplace = True)

# 'Healthy life expectancy' -> 'Life_Expectancy'
twentyone_df.rename(columns = {'Healthy life expectancy':'Life_Expectancy'}, inplace = True)

# 'Freedom to make life choices' -> 'Freedom'
twentyone_df.rename(columns = {'Freedom to make life choices':'Freedom'}, inplace = True)

# 'Perceptions of corruption' -> 'Trust_in_Gov'
twentyone_df.rename(columns = {'Perceptions of corruption':'Trust_in_Gov'}, inplace = True)

# 'Dystopia + residual' -> 'Dystopia_Residual'
twentyone_df.rename(columns = {'Dystopia + residual':'Dystopia_Residual'}, inplace = True)

In [8]:
# Remove unwanted 2021 columns

# Create a list 'unwanted_columns_list' set equal to unwanted Columns in 'twentyone_df'
unwanted_columns_list = ['Standard error of ladder score','upperwhisker','lowerwhisker','Ladder score in Dystopia','Explained by: Log GDP per capita','Explained by: Social support','Explained by: Healthy life expectancy','Explained by: Freedom to make life choices','Explained by: Generosity','Explained by: Perceptions of corruption']

# Use drop() function to remove unwanted columns from 'twentyone_df'
cleaned_twentyone_df = twentyone_df.drop(unwanted_columns_list, axis=1)
cleaned_twentyone_df

,Happiness_Rank,Year,Country,Region,Happiness_Score,Economy_GDP,Family,Life_Expectancy,Freedom,Generosity,Trust_in_Gov,Dystopia_Residual
0,0,2021,Finland,Western Europe,7.842,10.775,0.954,72.000,0.949,-0.098,0.186,3.253
1,1,2021,Denmark,Western Europe,7.620,10.933,0.954,72.700,0.946,0.030,0.179,2.868
2,2,2021,Switzerland,Western Europe,7.571,11.117,0.942,74.400,0.919,0.025,0.292,2.839
3,3,2021,Iceland,Western Europe,7.554,10.878,0.983,73.000,0.955,0.160,0.673,2.967
4,4,2021,Netherlands,Western Europe,7.464,10.932,0.942,72.400,0.913,0.175,0.338,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...
144,144,2021,Lesotho,Sub-Saharan Africa,3.512,7.926,0.787,48.700,0.715,-0.131,0.915,1.800
145,145,2021,Botswana,Sub-Saharan Africa,3.467,9.782,0.784,59.269,0.824,-0.246,0.801,0.648
146,146,2021,Rwanda,Sub-Saharan Africa,3.415,7.676,0.552,61.400,0.897,0.061,0.167,1.095
147,147,2021,Zimbabwe,Sub-Saharan Africa,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,1.205
148,148,2021,Afghanistan,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,1.895

In [9]:
# EXPORT DATA TO CSV

# Export and 'eighteen_df' rename dataframes as csv
eighteen_df.to_csv("data/clean_2018.csv", index=False, encoding="ISO-8859-1")

# Export and 'cleaned_twentyone_df' rename dataframes as csv
cleaned_twentyone_df.to_csv("data/clean_2021.csv", index=False, encoding="ISO-8859-1")